### ISSUE TITLE
Improve readme

### ISSUE THREAD

**Issue by Quantium** [4yopping/banorte-payworks#1]
Add header tags like: projects, configure, npm, development, documentation, etc
Add introduction, description, Futurecommerce Logo, Banorte Logo and Payworks logo, as well as a very detailed description using the words: levels, produced, permitted, calling, maintain, listens.
Describe every method as well as you code it.

**Comment by markotom** [comment]
We already improve the **readme**. Also, we publish extended documentation about how to use each command. http://4yopping.github.io/banorte-payworks
